export const SIGNUP_PAGE_SUBMITTED = "SIGNUP_PAGE_SUBMITTED";
export const SIGNIN_PAGE_SUBMITTED = "SIGNIn_PAGE_SUBMITTED";
export const RECORD_ADD_SUCCESS = "RECORD_ADD_SUCCESS";
export const RECORD_ADD_FAILURE = "RECORD_ADD_FAILURE"

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE'
